services:
  web-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resolutahubos-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Sao_Paulo
    env_file:
      - ../.env
    networks:
      - resolutahubos-network
      - telegram_torrent_telegram-torrent-network

  web-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resolutahubos-frontend
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - TZ=America/Sao_Paulo
      - VITE_API_URL=http://localhost:8000
    networks:
      - resolutahubos-network
    depends_on:
      - web-backend

networks:
  resolutahubos-network:
    driver: bridge
  telegram_torrent_telegram-torrent-network:
    external: true
